'use strict';
const assert=require('node:assert/strict');
const T=require('./trial.js'),E=require('./engine.js'),level=require('./levels.js')[0];
const base=Array(25).fill(0);base[24]=1;base[15]=2;
const notes=[{index:3,excluded:true}];
const pending=T.create(base,notes);
const trial=T.choose(pending,base,1);
assert.equal(pending.root,null);assert.equal(trial.root,1);
base[24]=0;notes[0].excluded=false;
assert.equal(trial.baseBoard[24],1);assert.equal(trial.baseNotes[0].excluded,true);
const restored=T.restore(trial);
assert.equal(restored.board[1],0);assert.equal(restored.board[15],2);assert.equal(restored.board[24],1);
assert.deepEqual(restored.notes,[{index:3,excluded:true},{index:1,excluded:false}]);
const rejected=T.restore(trial,true);
assert.equal(rejected.board[1],1);assert.deepEqual(rejected.notes.at(-1),{index:1,excluded:true});
restored.board[15]=0;restored.notes[0].excluded=false;
assert.equal(trial.baseBoard[15],2);assert.equal(trial.baseNotes[0].excluded,true);
const copy=T.clone(trial);copy.baseBoard[0]=2;copy.baseNotes[0].excluded=false;
assert.equal(trial.baseBoard[0],0);assert.equal(trial.baseNotes[0].excluded,true);
assert.throws(()=>T.choose(trial,base,2));assert.throws(()=>T.choose(pending,base,15));
assert.deepEqual(T.restore(pending).board,pending.baseBoard);
assert.equal(T.restore(pending,true).notes.length,1);
const solution=E.solve(level)[0],good=Array(25).fill(1);
solution.forEach((c,r)=>good[r*5+c]=2);
assert.deepEqual(T.contradictions(level,good),[]);
const noRow=Array(25).fill(0);noRow.fill(1,0,5);
assert(T.contradictions(level,noRow).some(x=>x.includes('第 1 行')));
const noCol=Array(25).fill(0);for(let r=0;r<5;r++)noCol[r*5]=1;
assert(T.contradictions(level,noCol).some(x=>x.includes('第 1 列')));
const noRegion=Array(25).fill(0);noRegion[15]=1;
assert(T.contradictions(level,noRegion).some(x=>x.includes('区域 D')));
const duplicate=Array(25).fill(0);duplicate[0]=duplicate[1]=2;
assert(T.contradictions(level,duplicate).some(x=>x.includes('多只猫')));
const partial=Array(25).fill(0);partial[1]=2;
assert.deepEqual(T.contradictions(level,partial),[]);
const nearSingleton=Array(25).fill(0);nearSingleton[10]=2;
assert(T.contradictions(level,nearSingleton).some(x=>x.includes('区域 D')));
console.log('PASS checkpoint isolation, restore/exclude, note preservation, cloning, invalid roots, row/column/region dead ends, neighboring dead ends, conflicts and valid boards.');
